---
driver:
 # name: docker
  #socket: <%= ENV['DOCKER_HOST'] %>
  #use_sudo: false
  #privileged: true
  name: vagrant
  synced_folders:
   - ['.', '/home/vagrant/my-project']
  vagrantfiles:
   - set-proxy.rb

  
provisioner:
  name: chef_zero
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  https_proxy: <%= ENV['HTTPS_PROXY'] %> 
  data_bags_path: test/fixtures/data_bags

platforms:
- name: centos-6.6
  driver_config:
    image: centos:6.6
    platform: centos

suites:
- name: default
  driver:
    vm_hostname: test-centos-server
  run_list: 
    - recipe[spacewalk-server]
    - recipe[spacewalk-server::first_user]
    - recipe[spacewalk-server::iptables]
    - recipe[spacewalk-server::rhel]
  attributes: {}
